# Source: r2-ue-compose/templates/compose.yaml

services:
  gateway:
    depends_on:
      - web
      - be
      - redis
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:8080
  web:
    build: ./web
    image: r2-web
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.50"
  be:
    # build: ./be-demo
    # image: r2-be-demo
    build: ./be-high-level
    image: r2-be-high-level
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.50"
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.50"
